# Generated by Django 4.2.3 on 2023-12-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="messages",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="messaging.message"
            ),
        ),
    ]
