# Generated by Django 4.2.3 on 2023-11-17 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("last_edited", models.DateTimeField(auto_now=True)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("READ", "Read")],
                        default="PENDING",
                        max_length=128,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("NEW_MESSAGE", "New Message"),
                            ("NEW_PROPOSAL", "New Proposal"),
                            ("NEW_PROJECT", "New Project"),
                            ("PROJECT_UPDATE", "Project Update"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "proposal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to="projects.proposal",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
